// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;
 
[assembly: AssemblyVersion("2012.3.24.1845")]
[assembly: AssemblyFileVersion("2012.3.24.1845")]
